//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repuestos_Araucania.Models.Productos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class productos
    {
        public int ID { get; set; }
        public string CÓDIGO { get; set; }
        public string NOMBRE { get; set; }
        public string PROVEEDOR { get; set; }
        public string DESCRIPCIÓN { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Nullable<double> PRECIO { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Nullable<double> MARGEN { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Nullable<double> COSTO { get; set; }

        [DisplayFormat(DataFormatString = "{0:N0}", ApplyFormatInEditMode = false)]
        public Nullable<double> NETO { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> MODIFICADO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<double> STOCK { get; set; }
        public bool MARCAR { get; set; }
    }
}
